services:
  jupyter:
    build: .
    volumes:
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    container_name: jupyter_notebook
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--notebook-dir=/app/notebooks"]
